### ISSUE TITLE
Autoexecution of macro on Mac

### ISSUE THREAD

**Issue by revelunt** [akmontoya/Oslo18#1]
Hi Amanda, 

Just stumbled upon this repository and saw that you did not know how to make the macro auto-executed on mac. I have figured out this when Andi was in our Comm department (took a several class with him back in years, as you would expect). The trick is to locate the script folder that is sitting inside of the SPSS program itself. Please see attached pdf for the details (the file has been documented when I was using SPSS version 22, but am still using this trick with version 24 and onwards). In case I am also attaching the "StartClient_.py" file for the reference, which you should change the location of "process.sps" file paths within that script. Let me know if you have any questions.

Best,
Jin

[Instructions for autoexecution of PROCESS for Mac.pdf](https://github.com/akmontoya/Oslo18/files/1622213/Instructions.for.autoexecution.of.PROCESS.for.Mac.pdf)
[StartClient_.py.zip](https://github.com/akmontoya/Oslo18/files/1622217/StartClient_.py.zip)

**Comment by akmontoya** [comment]
Thank you Jin!
This is really helpful!

Amanda

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[image: The Ohio State University]

Amanda Kay Montoya, M.S.
*Treasurer*
*Council of Graduate Students*
2088 Ohio Union
1739 N. High Street
Columbus, OH 43210

*cgs.osu.edu <http://cgs.osu.edu>*


*PhD Candidate*

*Department of Psychology*
1827 Neil Avenue
216 Lazenby Hall
The Ohio State University
Columbus, OH 43210 USA


pronouns: she, her, hers
email: montoya.29@osu.edu
phone: (206) 353-7337

website: akmontoya.com

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
